FROM nginxproxy/nginx-proxy:0.8.0

COPY ./nginxproxy/custom_proxy.conf /etc/nginx/conf.d/custom_proxy.conf

# RUN unlink /var/log/nginx/error.log && touch /var/log/nginx/error.log
# RUN unlink /var/log/nginx/access.log && touch /var/log/nginx/access.log
