version: "2"

volumes:
  kozimo_nginxproxy_production_nginx_vhost:
    name: kozimo_nginxproxy_production_nginx_vhost
  kozimo_nginxproxy_production_nginx_html:
    name: kozimo_nginxproxy_production_nginx_html
  kozimo_nginxproxy_production_nginx_certs:
    name: kozimo_nginxproxy_production_nginx_certs
  kozimo_nginxproxy_production_ssl_acme:
    name: kozimo_nginxproxy_production_ssl_acme
  # kozimo_nginxproxy_production_nginx_logs:
  #   name: kozimo_nginxproxy_production_nginx_logs

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: kozimo_nginxproxy_production_nginx
    container_name: kozimo_nginxproxy_production_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - kozimo_nginxproxy_production_nginx_certs:/etc/nginx/certs
      - kozimo_nginxproxy_production_nginx_vhost:/etc/nginx/vhost.d
      - kozimo_nginxproxy_production_nginx_html:/usr/share/nginx/html
      # - kozimo_nginxproxy_production_nginx_logs:/var/log/nginx/
    networks:
      - kozimo_nginxproxy_production_network

  ssl:
    image: nginxproxy/acme-companion:2.1.0
    container_name: kozimo_nginxproxy_production_ssl
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - kozimo_nginxproxy_production_ssl_acme:/etc/acme.sh
    networks:
      - kozimo_nginxproxy_production_network

networks:
  kozimo_nginxproxy_production_network:
    name: kozimo_nginxproxy_production_network
